fix errors for spacemacs

diff --git a/herbstluftwm/autostart b/herbstluftwm/autostart
--- a/herbstluftwm/autostart
+++ b/herbstluftwm/autostart
@@ -145,6 +145,7 @@ hc keybind $Mod-Control-Right   resize right +$resizestep
 [ "$(uname -n)" = "ultimate-lnx" ] && hc attr settings.default_frame_layout vertical || hc attr settings.default_frame_layout horizontal
 
 ## tags
+if true; then	# single monitor
 #tag_names=("  " "  " "  " "  " "  " "   " "   " "  " "  " "  " )
 #tag_names=("WEB" "TERM" "FILE" "MEDIA" "GIMP": "MISC" "CODE" "RRENT" "REDDIT" "CHAT")
 #tag_names=("I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")
@@ -175,6 +176,64 @@ hc foreach T tags.by-name. sprintf ATTR '%c.tiling.root.algorithm' T set_attr AT
 hc keybind $Mod-period use_index +1 --skip-visible
 hc keybind $Mod-comma  use_index -1 --skip-visible
 
+else	# multi monitors
+
+mon1_names=( 1_{1..5} ) # tag names for monitor 1
+mon2_names=( 2_{1..5} ) # tag names for monitor 2
+fallback_names=( {1..5} ) # tag names for all other monitors
+tag_keys=( {1..9} 0 )
+
+hc rename default "${mon1_names[0]}" || true
+for tag in "${mon1_names[@]}" "${mon2_names[@]}" "${fallback_names[@]}" ; do
+    hc try silent add "$tag"
+done
+
+for i in ${!tag_keys[@]} ; do
+    key="${tag_keys[$i]}"
+    # the keybinding works as follows: the or executes the commands separated by
+    # CASE and stops executing them after the first of those succeeds.
+    # the first command is: check that we are on monitor 3 and can switch to tag "${mon1_names[$i]}"
+    # if only one of these two steps fail, try the second one (and so one).
+    # The setup for two monitors is as follows:
+    hc keybind "$Mod-$key" \
+        or CASE and . compare monitors.focus.index = 0 . use "${mon1_names[$i]}" \
+           CASE and . compare monitors.focus.index = 1 . use "${mon2_names[$i]}" \
+           CASE use "${fallback_names[$i]}"
+    hc keybind "$Mod-Shift-$key" \
+        or CASE and . compare monitors.focus.index = 0 . move "${mon1_names[$i]}" \
+           CASE and . compare monitors.focus.index = 1 . move "${mon2_names[$i]}" \
+           CASE move "${fallback_names[$i]}"
+done
+
+# cycle through tags
+# add additional information in order to cycle only through a monitor's tags
+# and not through all tags
+define-tag-cycle() {
+    local n=$#
+    local tags=( "$@" )
+    for i in "${!tags[@]}" ; do
+        local t="${tags[$i]}"
+        hc chain , new_attr string tags.by-name."$t".my_previous_tag \
+                 , set_attr tags.by-name."$t".my_previous_tag "${tags[$(((i - 1 + n) % n))]}" \
+                 , new_attr string tags.by-name."$t".my_next_tag \
+                 , set_attr tags.by-name."$t".my_next_tag "${tags[$(((i + 1) % n))]}"
+    done
+}
+
+define-tag-cycle "${mon1_names[@]}"
+define-tag-cycle "${mon2_names[@]}"
+define-tag-cycle "${fallback_names[@]}"
+
+# cycle through tags
+# check whether the current tag as a custom "next tag" configured
+# if yes, jump to that one, otherwise fall back to ordinary use_index +1
+hc keybind $Mod-period or , substitute NEXT tags.focus.my_next_tag use NEXT  \
+                          , use_index +1 --skip-visible
+hc keybind $Mod-comma  or , substitute PREV tags.focus.my_previous_tag use PREV  \
+                          , use_index +1 --skip-visible
+
+fi      # end of single monitor
+                   
 
 hc keybind $Mod-r remove
 hc keybind $Mod-s floating toggle
@@ -269,6 +328,8 @@ herbstclient set tree_style '╾│ ├└╼─┐'
 #hc set_monitors 2560x1600+0+0 3440x1440+2560+0
 # or simply:
 hc detect_monitors
+
+#herbstclient set_monitors 2560x2880+0+0 3840x2160+2560+0
 
 # find the panel
 #panel=~/.config/herbstluftwm/panel.sh
